
@rootApi = http://localhost:8000

@userApi = {{rootApi}}/api/v1/user

@burrowApi = {{rootApi}}/api/v1/burrow

@bookApi = {{rootApi}}/api/v1/book

@reviewApi = {{rootApi}}/api/v1/review



### server request testing
GET {{rootApi}}

# ============ user API here =============
### get user
GET  {{userApi}}

### create user
POST  {{userApi}}
Content-Type: application/json

{
    "role": "student",
    "fName": "Sita",
    "lName": "Smith",
    "phone": "34653453",
    "address": "somewhere in Australia",
    "email": "sita@email.com",
    "password": "123456"
}


# ============ Book api 
### fetch all book
GET {{bookApi}}
Authorization: 6497a013e40152afd6a992a3

# ======== burrow api
### fetch
GET  {{burrowApi}}
Authorization: 6497cf2eaee2d920dcb2aa54


### create new burrow record
POST  {{burrowApi}}
Content-Type: application/json

{
    "bookId": "64a8a1458bdb18e8ec429572",
    "BookName": "Python Programming",
    "thumbnail": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn2.penguin.com.au%2Fcovers%2Foriginal%2F9781593278229.jpg&f=1&nofb=1&ipt=6a9f4bba59419a8cd6d58f5655f90c13879dad0d64f1e976cd7f6ec970267e17&ipo=images",
    "userId": "asljflj02840",
    "userName": "64983507452b879954cdcedc",
    "returnDate": "2023-12-12"
}


# ========== review API ============

### get review
GET {{reviewApi}}